apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: my-githubapp-runner
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      repository: your-username/your-repo
